### ISSUE TITLE
Very nice WeChat UI component 

### ISSUE THREAD

**Issue by neozhu** [MatrixAges/light-design#11]
能否再丰富一些例子,比例常用list, card, profile, form, map, home page,login 多种布局。

**Comment by MatrixAge** [comment]
额，由于还没准备发布1.0，所以我没有进行任何推广，现在相当于内测阶段，一切都在循序渐进地推进。

你说的上述这些例子会以一个示例小程序应用的方式出来，不过不是现在，但一定会有，可能是在下半年。

**Comment by neozhu** [comment]
相信将来一定会非常受欢迎
