### ISSUE TITLE
好久没有更新了,还在开发吗

### ISSUE THREAD

**Issue by neozhu** [MatrixAges/light-design#18]

**Comment by MatrixAge** [comment]
额，现在兴趣点在linkcase上，light design是我今年长期计划的一部分。

linkcase是一个用于管理书签、收藏的跨平台应用，目前正在紧锣密鼓开发当中：
![image](https://user-images.githubusercontent.com/25472851/122339931-3bb7f680-cf74-11eb-9b2b-abe438a5d012.png)

light design 目前还缺少十几个组件、使用light design构建的小程序电商应用，以及基于esbuild的小程序框架jax，还有light design的白皮书《Way of design：设计之道》，这些事情我一直都有在思考和记录。

肯定会抽时间发布出来，light design 1.0，这个主要看个人状态，状态好的时候文思泉涌，妙笔生花，状态不好是不会为了做而做的。

因为目前的工作主要是在web方面，而不仅仅是小程序，而且本人也渐渐觉得不太适合打工了，身体吃不消，也没啥意义，所以得开始做一些有商业化前景的项目，这个稍微比仅因为热爱而做light design优先级高点，也更加健康一点，毕竟赚钱是最直接的反馈，虽然light design也可以商业化，但并不合适。
